#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a\
     location /redirect_me {\
        return 301 https://github.com;\
     }" /etc/nginx/sites-enabled/default
sudo service nginx restart
