#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo touch /var/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/html/404.html > /dev/null
sudo sed -i "/listen 80 default_server;/a\
     location /redirect_me {\
        return 301 https://github.com;\
     }\
     error_page 404 /404.html;\
     location /404 {\
        root /var/www/html;\
        internal;\
    }" /etc/nginx/sites-enabled/default

sudo service nginx restart
